const fs = require("fs")

// ─── 1. PÁGINA GENÉRICA /[slug]/page.tsx ─────────────────────────────────────
const slugPage = [
'"use client"',
'import { Suspense, useEffect, useState } from "react"',
'import { useParams } from "next/navigation"',
'',
'interface Cabin { id: string; name: string; capacity: number; base_price_night: number }',
'interface TenantData { business_name: string; owner_whatsapp: string }',
'',
'function SlugInner() {',
'  const params = useParams()',
'  const slug = params.slug as string',
'  const [tenant, setTenant] = useState<TenantData | null>(null)',
'  const [cabins, setCabins] = useState<Cabin[]>([])',
'  const [loading, setLoading] = useState(true)',
'  const [notFound, setNotFound] = useState(false)',
'',
'  useEffect(function() {',
'    if (!slug) return',
'    fetch("/api/tenant/" + slug + "/cabins")',
'      .then(function(r) {',
'        if (!r.ok) { setNotFound(true); setLoading(false); return null }',
'        return r.json()',
'      })',
'      .then(function(d) {',
'        if (!d) return',
'        setTenant(d.tenant)',
'        setCabins(d.cabins || [])',
'        setLoading(false)',
'      })',
'      .catch(function() { setNotFound(true); setLoading(false) })',
'  }, [slug])',
'',
'  function fmt(n: number) { return "$" + n.toLocaleString("es-CL") }',
'',
'  if (loading) return (',
'    <div style={{ background: "#0a0f0a", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>',
'      <div style={{ color: "#4a6a48", fontFamily: "sans-serif", fontSize: "13px" }}>Cargando...</div>',
'    </div>',
'  )',
'',
'  if (notFound || !tenant) return (',
'    <div style={{ background: "#0a0f0a", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>',
'      <div style={{ color: "#4a6a48", fontFamily: "sans-serif", fontSize: "13px" }}>Cabañas no encontradas</div>',
'    </div>',
'  )',
'',
'  const parts = tenant.business_name.split(" ")',
'  const first = parts[0]',
'  const rest = parts.slice(1).join(" ")',
'  const wa = tenant.owner_whatsapp ? tenant.owner_whatsapp.replace(/[^0-9]/g, "") : ""',
'',
'  return (',
'    <div style={{ fontFamily: "Georgia, serif", background: "#0a0f0a", minHeight: "100vh", color: "#f0ede8" }}>',
'',
'      {/* NAV */}',
'      <div style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 50, background: "rgba(10,15,10,0.92)", borderBottom: "1px solid #1a261a", padding: "14px 24px", display: "flex", alignItems: "center", justifyContent: "space-between", backdropFilter: "blur(10px)" }}>',
'        <div style={{ fontFamily: "Georgia, serif", fontSize: "18px", letterSpacing: "4px", textTransform: "uppercase" }}>',
'          <span style={{ color: "#e8d5a3" }}>{first}</span>',
'          {rest && <span style={{ color: "#7ab87a" }}>{" " + rest}</span>}',
'        </div>',
'        {wa && (',
'          <a href={"https://wa.me/" + wa} target="_blank" rel="noopener noreferrer"',
'            style={{ background: "#25D366", color: "#000", border: "none", borderRadius: "8px", padding: "8px 16px", fontSize: "12px", fontWeight: 700, textDecoration: "none", fontFamily: "sans-serif" }}>',
'            {"WhatsApp"}',
'          </a>',
'        )}',
'      </div>',
'',
'      {/* HERO */}',
'      <div style={{ paddingTop: "120px", paddingBottom: "40px", textAlign: "center", background: "linear-gradient(180deg, #0a1208 0%, #0a0f0a 100%)", padding: "80px 24px 40px" }}>',
'        <div style={{ fontSize: "10px", letterSpacing: "3px", textTransform: "uppercase", color: "#7ab87a", marginBottom: "12px", fontFamily: "sans-serif" }}>Alojamiento · Sur de Chile</div>',
'        <div style={{ fontFamily: "Georgia, serif", fontSize: "clamp(28px, 5vw, 52px)", fontWeight: 700, color: "#f0ede8", lineHeight: 1.1, marginBottom: "16px" }}>',
'          <span style={{ color: "#e8d5a3" }}>{first}</span>',
'          {rest && <span style={{ color: "#b8d8a0" }}>{" " + rest}</span>}',
'        </div>',
'        <div style={{ fontFamily: "sans-serif", fontSize: "15px", color: "#8ab888", maxWidth: "360px", margin: "0 auto 24px", lineHeight: 1.7 }}>',
'          {"Reserva directo con el propietario. Sin intermediarios."}',
'        </div>',
'      </div>',
'',
'      {/* CABAÑAS */}',
'      <div style={{ padding: "0 16px 32px", maxWidth: "800px", margin: "0 auto" }}>',
'        <div style={{ fontSize: "10px", letterSpacing: "2.5px", textTransform: "uppercase", color: "#4a6a48", marginBottom: "12px", fontFamily: "sans-serif" }}>{"Elige tu caba\u00f1a"}</div>',
'        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "12px" }}>',
'          {cabins.map(function(c) {',
'            return (',
'              <div key={c.id} style={{ background: "#111a11", border: "1px solid #2a3a2a", borderRadius: "14px", padding: "20px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}>',
'                <div style={{ display: "inline-flex", alignItems: "center", gap: "4px", background: "#7ab87a14", border: "1px solid #7ab87a22", color: "#7ab87a", fontSize: "9px", padding: "2px 7px", borderRadius: "10px", marginBottom: "14px", fontFamily: "sans-serif" }}>',
'                  <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "#7ab87a", display: "inline-block" }}/>',
'                  Disponible',
'                </div>',
'                <div style={{ fontFamily: "Georgia, serif", fontSize: "18px", color: "#e8d5a3", marginBottom: "4px" }}>{c.name}</div>',
'                <div style={{ fontSize: "12px", color: "#8a9e88", marginBottom: "14px", fontFamily: "sans-serif" }}>{"Hasta " + c.capacity + " personas"}</div>',
'                <div style={{ fontFamily: "Georgia, serif", fontSize: "30px", color: "#c8d8c0", marginBottom: "2px" }}>{fmt(c.base_price_night)}</div>',
'                <div style={{ fontSize: "11px", color: "#6a8a68", marginBottom: "16px", fontFamily: "sans-serif" }}>por noche</div>',
'                <a href={"/reservar?cabin_id=" + c.id + "&cabin_name=" + encodeURIComponent(c.name) + "&price=" + c.base_price_night + "&capacity=" + c.capacity}',
'                  style={{ display: "block", width: "100%", boxSizing: "border-box", background: "#7ab87a", color: "#0a0f0a", borderRadius: "10px", padding: "12px", fontSize: "13px", fontWeight: 700, textAlign: "center", textDecoration: "none", fontFamily: "sans-serif" }}>',
'                  {"Reservar \u2192"}',
'                </a>',
'              </div>',
'            )',
'          })}',
'        </div>',
'      </div>',
'',
'      {/* FOOTER */}',
'      <div style={{ borderTop: "1px solid #1a261a", padding: "20px", textAlign: "center", fontFamily: "sans-serif" }}>',
'        <div style={{ fontSize: "10px", color: "#3a5a38", letterSpacing: "1.5px", textTransform: "uppercase" }}>',
'          {"Reservas gestionadas por "}<a href="https://takai.cl" style={{ color: "#5a7a58", textDecoration: "none" }}>TAKAI.CL</a>',
'        </div>',
'      </div>',
'    </div>',
'  )',
'}',
'',
'export default function SlugPage() {',
'  return (',
'    <Suspense fallback={<div style={{ background: "#0a0f0a", minHeight: "100vh" }}/>}>',
'      <SlugInner />',
'    </Suspense>',
'  )',
'}',
]

fs.mkdirSync("app/[slug]", { recursive: true })
fs.writeFileSync("app/[slug]/page.tsx", slugPage.join("\n") + "\n")
console.log("✓ app/[slug]/page.tsx creado")

// ─── 2. TRINIDAD page.tsx COMPLETA con Licanray + mapa ────────────────────────
const trinidadPage = [
'"use client"',
'import { Suspense, useEffect, useState } from "react"',
'',
'// Coordenadas GPS de Licanray, Lago Calafquén',
'const MAP_URL = "https://www.google.com/maps/search/Caba%C3%B1as+Trinidad+Licanray/@-39.4833,-72.1500,14z"',
'const MAP_LABEL = "Licanray, Lago Calafqu\u00e9n"',
'const TAG = "Licanray \u00b7 Lago Calafqu\u00e9n \u00b7 Regi\u00f3n de La Araucan\u00eda"',
'',
'interface Cabin { id: string; name: string; capacity: number; base_price_night: number }',
'',
'function MapCard() {',
'  return (',
'    <a',
'      href={MAP_URL}',
'      target="_blank"',
'      rel="noopener noreferrer"',
'      style={{ display: "inline-flex", alignItems: "center", gap: "10px", background: "#111a11", border: "1px solid #2a3a2a", borderRadius: "12px", padding: "10px 16px", textDecoration: "none", marginTop: "16px", cursor: "pointer" }}',
'    >',
'      <div style={{ width: "32px", height: "32px", background: "#1a2e1a", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px", flexShrink: 0 }}>',
'        {"\uD83D\uDCCD"}',
'      </div>',
'      <div>',
'        <div style={{ fontFamily: "sans-serif", fontSize: "12px", color: "#c8d8c0", fontWeight: 600, marginBottom: "2px" }}>{MAP_LABEL}</div>',
'        <div style={{ fontFamily: "sans-serif", fontSize: "10px", color: "#5a7a58", letterSpacing: "0.3px" }}>{"Ver c\u00f3mo llegar \u2192"}</div>',
'      </div>',
'    </a>',
'  )',
'}',
'',
'function TrinidadInner() {',
'  const [cabins, setCabins] = useState<Cabin[]>([])',
'  const [loading, setLoading] = useState(true)',
'',
'  useEffect(function() {',
'    fetch("/api/trinidad/cabins")',
'      .then(function(r) { return r.json() })',
'      .then(function(d) { setCabins(d.cabins || []); setLoading(false) })',
'      .catch(function() { setLoading(false) })',
'  }, [])',
'',
'  function fmt(n: number) { return "$" + n.toLocaleString("es-CL") }',
'',
'  return (',
'    <div style={{ fontFamily: "Georgia, serif", background: "#0a0f0a", minHeight: "100vh", color: "#f0ede8" }}>',
'',
'      <style>{"\\',
'        @media (max-width: 640px) { .hero-txt-tr { padding-top: 108px !important; } .cabins-grid-tr { grid-template-columns: 1fr !important; } }\\',
'        @media (min-width: 641px) { .sello-pc-tr { display: none !important; } .sello-fl-tr { display: flex !important; } }\\',
'        @media (max-width: 640px) { .sello-pc-tr { display: flex !important; } .sello-fl-tr { display: none !important; } }\\',
'      "}</style>',
'',
'      {/* HERO SVG */}',
'      <div style={{ position: "relative", width: "100%", overflow: "hidden", background: "#0a1208" }}>',
'        <svg style={{ display: "block", width: "100%", height: "auto", minHeight: "340px" }} viewBox="0 0 1200 520" preserveAspectRatio="xMidYMax slice">',
'          <defs>',
'            <linearGradient id="sky-tr" x1="0" y1="0" x2="0" y2="1">',
'              <stop offset="0%" stopColor="#070c0e"/><stop offset="60%" stopColor="#0a1018"/><stop offset="100%" stopColor="#0c1220"/>',
'            </linearGradient>',
'            <linearGradient id="lago-tr" x1="0" y1="0" x2="0" y2="1">',
'              <stop offset="0%" stopColor="#0a1828"/><stop offset="100%" stopColor="#060e18"/>',
'            </linearGradient>',
'            <linearGradient id="mist-tr" x1="0" y1="0" x2="0" y2="1">',
'              <stop offset="0%" stopColor="#0a0f0a" stopOpacity="0"/><stop offset="100%" stopColor="#0a0f0a" stopOpacity="1"/>',
'            </linearGradient>',
'            <radialGradient id="moon-tr" cx="50%" cy="50%" r="50%">',
'              <stop offset="0%" stopColor="#a0c0e0" stopOpacity="0.12"/><stop offset="100%" stopColor="#a0c0e0" stopOpacity="0"/>',
'            </radialGradient>',
'          </defs>',
'          <rect width="1200" height="520" fill="url(#sky-tr)"/>',
'          {/* estrellas */}',
'          <circle cx="80" cy="30" r="0.8" fill="#ffffff30"/><circle cx="250" cy="22" r="1" fill="#ffffff38"/>',
'          <circle cx="420" cy="50" r="0.7" fill="#ffffff28"/><circle cx="600" cy="18" r="0.9" fill="#ffffff22"/>',
'          <circle cx="780" cy="45" r="0.6" fill="#ffffff1a"/><circle cx="950" cy="25" r="0.8" fill="#ffffff30"/>',
'          <circle cx="1100" cy="55" r="0.7" fill="#ffffff20"/><circle cx="160" cy="70" r="0.5" fill="#ffffff15"/>',
'          {/* luna */}',
'          <circle cx="940" cy="75" r="75" fill="url(#moon-tr)"/>',
'          <circle cx="940" cy="75" r="4" fill="#c8e0f8" opacity="0.28"/>',
'          {/* volcán al fondo */}',
'          <path d="M500 200 L600 80 L700 200 Z" fill="#0d1828" opacity="0.6"/>',
'          <path d="M510 200 L600 95 L690 200 Z" fill="#0f1a2a" opacity="0.5"/>',
'          {/* montañas */}',
'          <path d="M0 310 L150 240 L280 270 L400 200 L520 240 L640 185 L750 215 L860 190 L980 220 L1100 200 L1200 230 L1200 520 L0 520Z" fill="#0f1a28" opacity="0.6"/>',
'          <path d="M0 360 L120 305 L240 340 L360 295 L480 325 L600 280 L720 310 L840 275 L960 305 L1080 285 L1200 300 L1200 520 L0 520Z" fill="#0c1520" opacity="0.9"/>',
'          {/* lago */}',
'          <path d="M0 400 L1200 390 L1200 460 L0 460Z" fill="url(#lago-tr)" opacity="0.5"/>',
'          <path d="M0 410 L200 405 L400 412 L600 406 L800 413 L1000 407 L1200 412 L1200 520 L0 520Z" fill="#060e18" opacity="0.7"/>',
'          {/* pinos */}',
'          <line x1="60" y1="460" x2="60" y2="390" stroke="#102010" strokeWidth="2.5"/>',
'          <polygon points="60,390 45,418 75,418" fill="#122012" opacity="0.85"/>',
'          <polygon points="60,404 43,432 77,432" fill="#142412" opacity="0.85"/>',
'          <polygon points="60,418 40,450 80,450" fill="#162812" opacity="0.85"/>',
'          <line x1="1140" y1="460" x2="1140" y2="385" stroke="#102010" strokeWidth="2.5"/>',
'          <polygon points="1140,385 1124,415 1156,415" fill="#122012" opacity="0.85"/>',
'          <polygon points="1140,400 1122,430 1158,430" fill="#142412" opacity="0.85"/>',
'          <polygon points="1140,415 1118,452 1162,452" fill="#162812" opacity="0.85"/>',
'          <line x1="300" y1="465" x2="300" y2="408" stroke="#0e1e0e" strokeWidth="2"/>',
'          <polygon points="300,408 288,428 312,428" fill="#122012" opacity="0.75"/>',
'          <polygon points="300,420 286,444 314,444" fill="#142412" opacity="0.75"/>',
'          <line x1="900" y1="465" x2="900" y2="405" stroke="#0e1e0e" strokeWidth="2.2"/>',
'          <polygon points="900,405 886,428 914,428" fill="#122012" opacity="0.8"/>',
'          <polygon points="900,418 884,444 916,444" fill="#142412" opacity="0.8"/>',
'          {/* niebla */}',
'          <rect x="0" y="440" width="1200" height="80" fill="url(#mist-tr)"/>',
'        </svg>',
'',
'        <div style={{ position: "absolute", inset: 0, background: "linear-gradient(180deg, #070c0e 0%, transparent 25%, transparent 55%, #0a0f0a 100%)", pointerEvents: "none" }}/>',
'',
'        {/* nombre en nav */}',
'        <div style={{ position: "absolute", top: 0, left: 0, right: 0, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 28px", zIndex: 10 }}>',
'          <div style={{ fontFamily: "Georgia, serif", fontSize: "22px", letterSpacing: "5px", color: "#e8d5a3", textShadow: "0 2px 12px #000000cc" }}>',
'            {"CABA\u00d1AS"}<span style={{ color: "#7ab87a" }}>{" TRINIDAD"}</span>',
'          </div>',
'          <div style={{ fontSize: "11px", color: "#a8c8a055", letterSpacing: "2px", textTransform: "uppercase" }}>{"Licanray"}</div>',
'        </div>',
'',
'        {/* texto hero */}',
'        <div className="hero-txt-tr" style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", textAlign: "center", padding: "40px 20px 16px" }}>',
'          <div style={{ fontSize: "11px", letterSpacing: "4px", textTransform: "uppercase", color: "#7ab87a", marginBottom: "14px" }}>{"Orillas del Lago Calafqu\u00e9n"}</div>',
'          <div style={{ fontFamily: "Georgia, serif", fontSize: "clamp(26px, 5vw, 48px)", fontWeight: 700, color: "#f0ede8", lineHeight: 1.15, marginBottom: "14px" }}>',
'            {"El lago como"}<br/><span style={{ color: "#b8d8a0" }}>{"tu ventana"}</span>',
'          </div>',
'          <div style={{ fontFamily: "sans-serif", fontSize: "clamp(12px, 1.6vw, 16px)", color: "#8ab888", lineHeight: 1.7, maxWidth: "380px", margin: "0 auto 16px" }}>',
'            {"Aguas cristalinas, bosque nativo y el Volc\u00e1n Villarrica como tel\u00f3n de fondo. En Licanray, a pasos del lago."}',
'          </div>',
'          <div style={{ display: "inline-flex", alignItems: "center", gap: "7px", background: "#ffffff07", border: "1px solid #ffffff12", borderRadius: "20px", padding: "6px 16px", fontFamily: "sans-serif", fontSize: "11px", color: "#9ab898" }}>',
'            <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#7ab87a", flexShrink: 0, display: "inline-block" }}/>',
'            {TAG}',
'          </div>',
'        </div>',
'      </div>',
'',
'      {/* MAPA */}',
'      <div style={{ padding: "20px 16px 0", maxWidth: "800px", margin: "0 auto" }}>',
'        <MapCard />',
'      </div>',
'',
'      {/* CABAÑAS */}',
'      <div style={{ padding: "20px 16px 6px", fontFamily: "sans-serif", maxWidth: "800px", margin: "0 auto" }}>',
'        <div style={{ fontSize: "10px", letterSpacing: "2.5px", textTransform: "uppercase", color: "#4a6a48", marginBottom: "10px" }}>{"Reserva tu caba\u00f1a"}</div>',
'        {loading ? (',
'          <div style={{ color: "#4a6a48", fontSize: "13px", padding: "16px 0" }}>Cargando...</div>',
'        ) : (',
'          <div className="cabins-grid-tr" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px", marginBottom: "4px" }}>',
'            {cabins.map(function(c) {',
'              return (',
'                <div key={c.id} style={{ background: "#111a11", border: "1px solid #2a3a2a", borderRadius: "14px", padding: "16px", display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center" }}>',
'                  <div style={{ display: "inline-flex", alignItems: "center", gap: "4px", background: "#7ab87a14", border: "1px solid #7ab87a22", color: "#7ab87a", fontSize: "9px", padding: "2px 7px", borderRadius: "10px", marginBottom: "12px" }}>',
'                    <span style={{ width: "4px", height: "4px", borderRadius: "50%", background: "#7ab87a", display: "inline-block" }}/>',
'                    Disponible',
'                  </div>',
'                  <div style={{ marginBottom: "10px" }}>',
'                    <svg width="40" height="36" viewBox="0 0 48 40" fill="none">',
'                      <path d="M24 4 L44 20 L44 38 L4 38 L4 20 Z" fill="#162618" stroke="#3a5a38" strokeWidth="1.5" strokeLinejoin="round"/>',
'                      <path d="M24 4 L44 20 L4 20 Z" fill="#1e3020" stroke="#3a5a38" strokeWidth="1.5" strokeLinejoin="round"/>',
'                      <rect x="18" y="26" width="12" height="12" rx="2" fill="#0d1a0d" stroke="#3a5a38" strokeWidth="1"/>',
'                    </svg>',
'                  </div>',
'                  <div style={{ fontFamily: "Georgia, serif", fontSize: "17px", color: "#e8d5a3", marginBottom: "4px" }}>{c.name}</div>',
'                  <div style={{ fontSize: "11px", color: "#8a9e88", marginBottom: "12px" }}>{"Hasta " + c.capacity + " personas"}</div>',
'                  <div style={{ fontFamily: "Georgia, serif", fontSize: "28px", color: "#c8d8c0", marginBottom: "2px" }}>{fmt(c.base_price_night)}</div>',
'                  <div style={{ fontSize: "10px", color: "#6a8a68", marginBottom: "14px" }}>por noche</div>',
'                  <a href={"/reservar?cabin_id=" + c.id + "&cabin_name=" + encodeURIComponent(c.name) + "&price=" + c.base_price_night + "&capacity=" + c.capacity}',
'                    style={{ display: "block", boxSizing: "border-box", width: "100%", background: "#7ab87a", color: "#0a0f0a", border: "none", borderRadius: "10px", padding: "11px", fontSize: "13px", fontWeight: 700, textAlign: "center", textDecoration: "none", fontFamily: "sans-serif" }}>',
'                    {"Reservar \u2192"}',
'                  </a>',
'                </div>',
'              )',
'            })}',
'          </div>',
'        )}',
'      </div>',
'',
'      {/* QUÉ HACER */}',
'      <div style={{ background: "#0d140d", padding: "16px", borderTop: "1px solid #1a261a", fontFamily: "sans-serif" }}>',
'        <div style={{ maxWidth: "800px", margin: "0 auto" }}>',
'          <div style={{ fontFamily: "Georgia, serif", fontSize: "17px", color: "#e8d5a3", marginBottom: "12px" }}>{"Qu\u00e9 hacer en Licanray"}</div>',
'          {[',
'            { ico: "\uD83C\uDFDE\uFE0F", name: "Lago Calafqu\u00e9n", desc: "Aguas de origen glaciar a pocos pasos \u2014 ideal para kayak, pesca y ba\u00f1os en verano" },',
'            { ico: "\uD83C\uDF0B", name: "Volc\u00e1n Villarrica", desc: "A 45 min \u2014 trekking hasta la cima de uno de los volcanes m\u00e1s activos de Sudam\u00e9rica" },',
'            { ico: "\u2668\uFE0F", name: "Termas de Co\u00f1aripe", desc: "Aguas termales naturales rodeadas de monta\u00f1a y bosque, a solo 20 min de Licanray" },',
'            { ico: "\uD83E\uDD7E", name: "Senderismo y miradores", desc: "Rutas en bosque nativo con vistas panor\u00e1micas al lago y la cordillera andina" },',
'          ].map(function(a) {',
'            return (',
'              <div key={a.name} style={{ display: "flex", gap: "10px", alignItems: "flex-start", marginBottom: "10px", paddingBottom: "10px", borderBottom: "1px solid #ffffff07" }}>',
'                <div style={{ width: "36px", height: "36px", background: "#162618", border: "1px solid #2a3820", borderRadius: "9px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px", flexShrink: 0 }}>{a.ico}</div>',
'                <div>',
'                  <div style={{ fontSize: "12px", fontWeight: 600, color: "#c8d8c0", marginBottom: "2px" }}>{a.name}</div>',
'                  <div style={{ fontSize: "11px", color: "#6a8a68", lineHeight: 1.5 }}>{a.desc}</div>',
'                </div>',
'              </div>',
'            )',
'          })}',
'        </div>',
'      </div>',
'',
'      {/* NORMAS */}',
'      <div style={{ background: "#0a0f0a", padding: "13px 16px", borderTop: "1px solid #1a261a", fontFamily: "sans-serif" }}>',
'        <div style={{ maxWidth: "800px", margin: "0 auto" }}>',
'          <div style={{ fontSize: "10px", fontWeight: 600, color: "#8a9e88", letterSpacing: "1.5px", textTransform: "uppercase", marginBottom: "7px" }}>Normas del lugar</div>',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "5px" }}>',
'            {["No mascotas", "No fiestas", "No visitas externas", "No fumar adentro", "No papeles al WC", "M\u00fasica moderada"].map(function(r) {',
'              return (',
'                <div key={r} style={{ display: "flex", alignItems: "center", gap: "5px", fontSize: "10px", color: "#6a8a68" }}>',
'                  <span style={{ color: "#c0504888", fontSize: "11px", fontWeight: 700 }}>{"\u00d7"}</span>',
'                  {r}',
'                </div>',
'              )',
'            })}',
'          </div>',
'        </div>',
'      </div>',
'',
'      {/* FOOTER */}',
'      <div style={{ textAlign: "center", padding: "12px", fontSize: "10px", color: "#5a7058", letterSpacing: "1.5px", textTransform: "uppercase", borderTop: "1px solid #1a261a", fontFamily: "sans-serif" }}>',
'        {"Caba\u00f1as Trinidad \u00b7 Licanray \u00b7 Lago Calafqu\u00e9n \u00b7 Chile"}',
'      </div>',
'    </div>',
'  )',
'}',
'',
'export default function TrinidadPage() {',
'  return (',
'    <Suspense fallback={<div style={{ background: "#0a0f0a", minHeight: "100vh" }}/>}>',
'      <TrinidadInner />',
'    </Suspense>',
'  )',
'}',
]

fs.writeFileSync("app/trinidad/page.tsx", trinidadPage.join("\n") + "\n")
console.log("✓ app/trinidad/page.tsx actualizado con Licanray + mapa")
